<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use TM\Core\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            [
                "id" => "1",
                "parent_id" => null,
                "_lft" => "1857",
                "_rgt" => "1932",
                "name_fa" => "تهران",
                "name_en" => "Tehran",
                "type" => "0",
                "region" => "IR-07",
                "latitude" => "35.705262263265716\n",
                "longitude" => "51.39884948730469",
            ],
            [
                "id" => "2",
                "parent_id" => null,
                "_lft" => "981",
                "_rgt" => "1032",
                "name_fa" => "اصفهان",
                "name_en" => "isfahan",
                "type" => "0",
                "region" => null,
                "latitude" => "32.65139",
                "longitude" => "51.679192",
            ],
            [
                "id" => "4",
                "parent_id" => null,
                "_lft" => "895",
                "_rgt" => "980",
                "name_fa" => "آذربایجان غربی",
                "name_en" => "azerbaijan-west",
                "type" => "0",
                "region" => null,
                "latitude" => "37.5296071",
                "longitude" => "45.0465487",
            ],
            [
                "id" => "5",
                "parent_id" => null,
                "_lft" => "873",
                "_rgt" => "894",
                "name_fa" => "ایلام",
                "name_en" => "ilam",
                "type" => "0",
                "region" => null,
                "latitude" => "33.638531",
                "longitude" => "46.422649",
            ],
            [
                "id" => "6",
                "parent_id" => null,
                "_lft" => "747",
                "_rgt" => "872",
                "name_fa" => "آذربایجان شرقی",
                "name_en" => "azerbaijan-east",
                "type" => "0",
                "region" => null,
                "latitude" => "38.246471",
                "longitude" => "48.295052",
            ],
            [
                "id" => "7",
                "parent_id" => null,
                "_lft" => "669",
                "_rgt" => "746",
                "name_fa" => "بوشهر",
                "name_en" => "bushehr",
                "type" => "0",
                "region" => null,
                "latitude" => "28.922041",
                "longitude" => "50.833092",
            ],
            [
                "id" => "8",
                "parent_id" => null,
                "_lft" => "613",
                "_rgt" => "668",
                "name_fa" => "چهار محال و بختیاری",
                "name_en" => "chahar-mahaal-bakhtiari",
                "type" => "0",
                "region" => null,
                "latitude" => "32.3555942",
                "longitude" => "50.8274267",
            ],
            [
                "id" => "9",
                "parent_id" => null,
                "_lft" => "581",
                "_rgt" => "612",
                "name_fa" => "خوزستان",
                "name_en" => "khuzestan",
                "type" => "0",
                "region" => null,
                "latitude" => "31.5317162",
                "longitude" => "49.8803281",
            ],
            [
                "id" => "10",
                "parent_id" => null,
                "_lft" => "507",
                "_rgt" => "580",
                "name_fa" => "خراسان رضوی",
                "name_en" => "khorasan-razavi",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "59.365671",
            ],
            [
                "id" => "11",
                "parent_id" => null,
                "_lft" => "449",
                "_rgt" => "506",
                "name_fa" => "خراسان جنوبی",
                "name_en" => "khorasan-south",
                "type" => "0",
                "region" => null,
                "latitude" => "32.8462159",
                "longitude" => "59.2911422",
            ],
            [
                "id" => "12",
                "parent_id" => null,
                "_lft" => "417",
                "_rgt" => "448",
                "name_fa" => "خراسان شمالی",
                "name_en" => "khorasan-north",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "13",
                "parent_id" => null,
                "_lft" => "373",
                "_rgt" => "416",
                "name_fa" => "زنجان",
                "name_en" => "zanjan",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "14",
                "parent_id" => null,
                "_lft" => "147",
                "_rgt" => "372",
                "name_fa" => "سیستان و بلوچستان",
                "name_en" => "sistan-baluchestan",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "15",
                "parent_id" => null,
                "_lft" => "87",
                "_rgt" => "146",
                "name_fa" => "فارس",
                "name_en" => "fars",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "16",
                "parent_id" => null,
                "_lft" => "1033",
                "_rgt" => "1048",
                "name_fa" => "قم",
                "name_en" => "qom",
                "type" => "0",
                "region" => "IR-26",
                "latitude" => "34.6399",
                "longitude" => "50.8759",
            ],
            [
                "id" => "17",
                "parent_id" => null,
                "_lft" => "1049",
                "_rgt" => "1098",
                "name_fa" => "قزوین",
                "name_en" => "qazvin",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "18",
                "parent_id" => null,
                "_lft" => "1823",
                "_rgt" => "1856",
                "name_fa" => "كهكيلويه و بويراحمد",
                "name_en" => "kohgiluyeh-boyer-ahmad",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "19",
                "parent_id" => null,
                "_lft" => "1771",
                "_rgt" => "1822",
                "name_fa" => "کرمان",
                "name_en" => "kerman",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "20",
                "parent_id" => null,
                "_lft" => "1643",
                "_rgt" => "1770",
                "name_fa" => "کرمانشاه",
                "name_en" => "kermanshah",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "21",
                "parent_id" => null,
                "_lft" => "1593",
                "_rgt" => "1642",
                "name_fa" => "کردستان",
                "name_en" => "kurdistan",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "22",
                "parent_id" => null,
                "_lft" => "1465",
                "_rgt" => "1592",
                "name_fa" => "گلستان",
                "name_en" => "golestan",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "23",
                "parent_id" => null,
                "_lft" => "1439",
                "_rgt" => "1464",
                "name_fa" => "گیلان",
                "name_en" => "gilan",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "24",
                "parent_id" => null,
                "_lft" => "1399",
                "_rgt" => "1438",
                "name_fa" => "مازندران",
                "name_en" => "mazandaran",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "25",
                "parent_id" => null,
                "_lft" => "1329",
                "_rgt" => "1398",
                "name_fa" => "مرکزی",
                "name_en" => "markazi",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "26",
                "parent_id" => null,
                "_lft" => "1273",
                "_rgt" => "1328",
                "name_fa" => "همدان",
                "name_en" => "hamadan",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "27",
                "parent_id" => null,
                "_lft" => "1225",
                "_rgt" => "1272",
                "name_fa" => "هرمزگان",
                "name_en" => "hormozgan",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "28",
                "parent_id" => null,
                "_lft" => "1181",
                "_rgt" => "1224",
                "name_fa" => "یزد",
                "name_en" => "yazd",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "29",
                "parent_id" => null,
                "_lft" => "1151",
                "_rgt" => "1180",
                "name_fa" => "البرز",
                "name_en" => "alborz",
                "type" => "0",
                "region" => null,
                "latitude" => "",
                "longitude" => "",
            ],
            [
                "id" => "30",
                "parent_id" => null,
                "_lft" => "1099",
                "_rgt" => "1150",
                "name_fa" => "لرستان",
                "name_en" => "lorestan",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "31",
                "parent_id" => null,
                "_lft" => "51",
                "_rgt" => "86",
                "name_fa" => "سمنان",
                "name_en" => "semnan",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "32",
                "parent_id" => null,
                "_lft" => "1",
                "_rgt" => "50",
                "name_fa" => "اردبیل",
                "name_en" => "ardabil",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "33",
                "parent_id" => "1",
                "_lft" => "1862",
                "_rgt" => "1863",
                "name_fa" => "تهران",
                "name_en" => "Tehran",
                "type" => "1",
                "region" => "IR-07",
                "latitude" => "35.7052",
                "longitude" => "51.3988",
            ],
            [
                "id" => "34",
                "parent_id" => "1",
                "_lft" => "1860",
                "_rgt" => "1861",
                "name_fa" => "اسلامشهر",
                "name_en" => "eslamshahr",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "35",
                "parent_id" => "16",
                "_lft" => "1044",
                "_rgt" => "1045",
                "name_fa" => "قم",
                "name_en" => "Qom",
                "type" => "1",
                "region" => "IR-26",
                "latitude" => "34.6417563",
                "longitude" => "50.8790297",
            ],
            [
                "id" => "37",
                "parent_id" => "2",
                "_lft" => "984",
                "_rgt" => "985",
                "name_fa" => "شاهین شهر و میمه",
                "name_en" => "Shahin Shahr",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "39",
                "parent_id" => "1",
                "_lft" => "1858",
                "_rgt" => "1859",
                "name_fa" => "شهر ری",
                "name_en" => "ShahreRey",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "40",
                "parent_id" => "4",
                "_lft" => "978",
                "_rgt" => "979",
                "name_fa" => "ارومیه",
                "name_en" => "Ouroomiyeh",
                "type" => "1",
                "region" => null,
                "latitude" => "37.5527145",
                "longitude" => "45.0766208",
            ],
            [
                "id" => "41",
                "parent_id" => "25",
                "_lft" => "1396",
                "_rgt" => "1397",
                "name_fa" => "اراک",
                "name_en" => "اراک",
                "type" => "1",
                "region" => null,
                "latitude" => "34.0953550",
                "longitude" => "49.7013490",
            ],
            [
                "id" => "43",
                "parent_id" => "10",
                "_lft" => "512",
                "_rgt" => "513",
                "name_fa" => "مشهد",
                "name_en" => "Mashhad",
                "type" => "1",
                "region" => null,
                "latitude" => "36.2879916",
                "longitude" => "59.6161252",
            ],
            [
                "id" => "49",
                "parent_id" => "9",
                "_lft" => "582",
                "_rgt" => "583",
                "name_fa" => "اهواز",
                "name_en" => "Ahwaz",
                "type" => "1",
                "region" => null,
                "latitude" => "31.3122629",
                "longitude" => "48.6736681",
            ],
            [
                "id" => "51",
                "parent_id" => "29",
                "_lft" => "1152",
                "_rgt" => "1153",
                "name_fa" => "کرج",
                "name_en" => "Karaj",
                "type" => "1",
                "region" => null,
                "latitude" => "35.8400190",
                "longitude" => "50.9390910",
            ],
            [
                "id" => "52",
                "parent_id" => "2",
                "_lft" => "982",
                "_rgt" => "983",
                "name_fa" => "اصفهان",
                "name_en" => "Isfahan",
                "type" => "1",
                "region" => null,
                "latitude" => "32.6540735",
                "longitude" => "51.6693107",
            ],
            [
                "id" => "53",
                "parent_id" => "15",
                "_lft" => "144",
                "_rgt" => "145",
                "name_fa" => "شیراز",
                "name_en" => "Shiraz",
                "type" => "1",
                "region" => null,
                "latitude" => "29.6095492",
                "longitude" => "52.5432758",
            ],
            [
                "id" => "55",
                "parent_id" => "10",
                "_lft" => "510",
                "_rgt" => "511",
                "name_fa" => "انابد",
                "name_en" => "Anabed",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "56",
                "parent_id" => "10",
                "_lft" => "514",
                "_rgt" => "515",
                "name_fa" => "باخرز",
                "name_en" => "Bakharz",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "57",
                "parent_id" => "10",
                "_lft" => "516",
                "_rgt" => "517",
                "name_fa" => "بجستان",
                "name_en" => "Bejestan",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "58",
                "parent_id" => "10",
                "_lft" => "542",
                "_rgt" => "543",
                "name_fa" => "بردسکن",
                "name_en" => "Bardaskan",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "59",
                "parent_id" => "10",
                "_lft" => "540",
                "_rgt" => "541",
                "name_fa" => "تایباد",
                "name_en" => "Taybad",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "60",
                "parent_id" => "10",
                "_lft" => "538",
                "_rgt" => "539",
                "name_fa" => "تربت جام",
                "name_en" => "Torbate_Jam",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "61",
                "parent_id" => "10",
                "_lft" => "536",
                "_rgt" => "537",
                "name_fa" => "تربت حیدریه",
                "name_en" => "Torbate_Heydariyyeh",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "62",
                "parent_id" => "10",
                "_lft" => "534",
                "_rgt" => "535",
                "name_fa" => "جغتای",
                "name_en" => "Joghatay",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "63",
                "parent_id" => "10",
                "_lft" => "532",
                "_rgt" => "533",
                "name_fa" => "چناران",
                "name_en" => "Chenaran",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "64",
                "parent_id" => "10",
                "_lft" => "530",
                "_rgt" => "531",
                "name_fa" => "خرو",
                "name_en" => "Khoro",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "65",
                "parent_id" => "10",
                "_lft" => "528",
                "_rgt" => "529",
                "name_fa" => "خلیل‌آباد",
                "name_en" => "Khalil_Abad",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "66",
                "parent_id" => "10",
                "_lft" => "526",
                "_rgt" => "527",
                "name_fa" => "خواف",
                "name_en" => "Khaf",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ],
            [
                "id" => "67",
                "parent_id" => "10",
                "_lft" => "524",
                "_rgt" => "525",
                "name_fa" => "درگز",
                "name_en" => "Daregaz",
                "type" => "0",
                "region" => null,
                "latitude" => null,
                "longitude" => null,
            ]
        ];
        foreach ($cities as $city) {
            City::query()->create($city);
        }
    }

}
